### PR TITLE
Unpin aiohttp dependency

### PR DESCRIPTION
**Pull request by joostlek**

### CODE REVIEW

**Comment by joostlek** [comment]
Oh, poetry lock wanted an update too

**Comment by joostlek** [comment]
Are you behind your pc already or should I do this in a few minutes

**Comment by DCSBL** [comment]
On it now :)

**Comment by DCSBL** [comment]
@joostlek Will this do or do we have to bump /unpin the package itself in the lockfile?

**Comment by joostlek** [comment]
This is fine!

**Comment by joostlek** [comment]
Like the requirements itself is just saying, any version >= 3.0.0 is fine.

When installing the lib directly via poetry it will install the lock one, if installed via pip it will just pick a version >= 3.

**Comment by DCSBL** [comment]
Here you go, do you pick this up at Core?

https://github.com/homewizard/python-homewizard-energy/releases/tag/v4.2.2

Should be available in a few minutes on PyPi

**Pull request merged**
